# Generated by Django 4.2.5 on 2023-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField()),
                ('title', models.CharField(max_length=51, verbose_name='Название')),
                ('genre', models.CharField(max_length=51, verbose_name='Жанр')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('director', models.CharField(max_length=51, verbose_name='Режиссер')),
                ('age', models.CharField(max_length=51, verbose_name='Возраст')),
                ('time', models.CharField(max_length=51, verbose_name='Время')),
                ('in_roles', models.CharField(max_length=250, verbose_name='В ролях')),
                ('description', models.TextField(verbose_name='Про фильм')),
                ('poster', models.ImageField(upload_to='films/', verbose_name='Постер фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
