# Generated by Django 4.2.5 on 2023-10-31 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField()),
                ('title', models.CharField(max_length=51, verbose_name='Название')),
                ('genre', models.CharField(max_length=51, verbose_name='Жанр')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('director', models.CharField(max_length=51, verbose_name='Режиссер')),
                ('age', models.CharField(max_length=51, verbose_name='Возраст')),
                ('avg_time', models.CharField(max_length=51, verbose_name='Среднее время серии')),
                ('in_roles', models.CharField(max_length=250, verbose_name='В ролях')),
                ('description', models.TextField(verbose_name='Про сериал')),
                ('poster', models.ImageField(upload_to='serials/', verbose_name='Постер сериала')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='serials.serials')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
