# Generated by Django 4.2.5 on 2023-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField()),
                ('title', models.CharField(max_length=51, verbose_name='Название')),
                ('genre', models.CharField(max_length=51, verbose_name='Жанр')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('age', models.CharField(max_length=51, verbose_name='Возраст')),
                ('avg_time', models.CharField(max_length=51, verbose_name='Среднее время серии')),
                ('description', models.TextField(verbose_name='Про аниме')),
                ('poster', models.ImageField(upload_to='anime/', verbose_name='Постер аниме')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
    ]
